### PR TITLE
Tweaks and test updates for PR 6116

### PR DESCRIPTION
**Pull request by cjbj**
Some test updates, parameter naming standardization, and the basic ValueError arg number fix. This doesn't solve the method/function [argument issue](https://github.com/php/php-src/pull/6116#pullrequestreview-487419587), but is a step forward.

### CODE REVIEW

**Comment by Girgias** [comment]
Sorry for the delay, had some technical issues: but for the mysqli extension I defined a new macro:
```c
#define ERROR_ARG_POS(arg_num) (getThis() ? (arg_num-1) : (arg_num))
```
And you use the ZPP arg value as the arg_num and that handles the OO/procedural API differences.

**Comment by cjbj** [comment]
> #define ERROR_ARG_POS(arg_num) (getThis() ? (arg_num-1) : (arg_num))

Thank you.  I guess it does make sense to leave it to the caller to decide what to pass to the zend layer. 

I've pushed the change.

**Comment by Girgias** [comment]
Great :D do you want me to merge and squash this and update this PR back on php-src?

**Comment by cjbj** [comment]
Can you merge 6116 to PHP master?  I don't think there is anything outstanding on it.  I will review other potential warning promotions when I get more time.

Thanks for all your work.

**Comment by Girgias** [comment]
Will do after a squash rebase

**Pull request merged**
